### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by MX10-AC2N** [protyposis/LocalAudioBroadcast#7]
Hello, and first of all a huge thank you for this software which works wonderfully with my Harman Kardon AVR265 amp.
However I note that there has been no update since 2015 and yet there is something to further improve the software .. I am thinking in particular of having to keep the sound on my pc which poses a problem with streaming ( Desynchronization ..) my solution plugged in an old headset on the sound output of the pc but it would be nice to be able to have only the sound output on Local Audio Broadcast. Another thing would be to be able to choose which application I want to stream or not .. And also to be able to choose the quality of reproduction, given by this fact more compatibility with the various upnp receivers. Another small thing given a high priority system for LocalAudioBroadcast  and Prevent the pc from going to sleep ..
In any case BRAVO for the great work you have done .. Hoping for a future update ..

**Comment by protyposis** [comment]
Thanks. There hasn't been any update from my side because I'm not using this any longer - which is also why there most likely won't be any further updates. But this is open source, and anyone can contribute improvements.

What you are asking here are multiple new major features that each likely take days to implement, and finding a volunteer taking up on that is rather unlikely. I'm sorry to say but please don't get your hopes up that this is ever going to happen.

**Comment by MX10-AC2N** [comment]
Thank you, and sorry to hear this but hey maybe a charitable soul will take over the coding of this great program.
Thank you again for all..

**Comment by Amunak** [comment]
> There hasn't been any update from my side because I'm not using this any longer

Is there something you use instead, or have you given up on sound broadcasting altogether?

**Comment by protyposis** [comment]
I used this to send Spotify music from my computer to my home theatre receiver and switched to a Chromecast when Spotify added Chromecast support.

**Comment by protyposis** [comment]
Closing due to repo archival.
